title: ML PLatform
description: >-
  ArmNN and Arm Compute Library
url: "https://mlplatform.org"
theme: jumbo-jekyll-theme
plugins:
  - jekyll-data
exclude:
    - .asset-cache
    - .sass-cache
    - _site
    - CODEOWNERS
    - build-site.sh
    - Gemfile
    - Gemfile.lock
    - README.md
permalink: /:categories/:title/
blog_images_dir: assets/images/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: false